### ISSUE TITLE
comparision against Realm

### ISSUE THREAD

**Issue by MarcinOrlowski** [rehacktive/waspdb#4]
Mind adding perfromance comparision against Realm?

**Comment by rehacktive** [comment]
sure I'll work on that.

**Comment by ghost** [comment]
If i'm allowed to express myself on this, i would say both do not serve the same purpose at all. 

Realm is meant as a replacement for a relational database, you can query it. 
Thus you have to extend RealmObject, replace List by RealmList, even replace List of basic String by a new List of RealmStringWrapper (or whatever you want to call it). 
It also comes at price, you APK takes 2 megabytes in the belly, and the internal data, god, i can't even tell. 

Waspdb is meant to be lightweight, and is "only" providing an easy way to perform an optimized Kryo serialization on the disk. You can not query it. 

Whether you need to use realm or waspdb is not about performance, but operations you need to perform on the saved data.

But since, performance comparison is always great, i expect waspdb to be faster.

**Comment by rehacktive** [comment]
Correct. Generally NoSQL databases (like WaspDb) don't have query support. 
It's a totally different approach. However it's possible to make some kind of comparison, like the one I did with the other databases (see documentation).
I've seen that Realm 1.0 is finally available, I'll try to do some test anyway.
